description = "Negative lookahead in VSCode search bar"
images = ["visual-studio-code-thumbnail.svg"]
# images = ["https://cdn.svgporn.com/logos/visual-studio-code.svg"]
title = "VSCode |> Regex in Search Bar (1)"
audio = []
date = "2020-07-20"
series = []
tags = []
videos = []